Fakebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('social.urls'), name='home')
]

Istudy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('social.urls'), name='home')
]

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User


class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        user_exists = User.objects.filter(username=self.cleaned_data['nome']).exists()
        if user_exists:
            self.adiciona_erro('Usuario já existe')
            valid = False

        return valid

    def adiciona_erro(self, mensagem):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS,forms.utils.ErrorList())
        errors.append(mensagem)

usuarios/views.py
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect
from usuarios.forms import *
from social.models import *
from django.contrib.auth.models import User
from django.views.generic.base import View


class RegistrarUsuarioView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            dados_form = form.cleaned_data
            usuario = User.objects.create_user(username=dados_form['nome'],
                                          email=dados_form['email'],
                                          password=dados_form['senha'])

            Usuario.objects.create(telefone=dados_form['telefone'],
                                           nome_empresa=dados_form['nome_empresa'],
                                           usuario=usuario)

            return redirect('login')

        return render(request, self.template_name, {'form': form})

usuarios/templates/base_usuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>ConnectedIn</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

usuarios/templates/login.html
{% extends "base_usuario.html" %}
{% block body %}
<form class="form-signin" role="form"
      action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Login</h2>
    <input id="id_username" name="username"
           class="form-control" placeholder="Nome" required autofocus>

    <input type="password" id="id_password" name="password"
           class="form-control" placeholder="Senha" required>

    <button class="btn btn-lg btn-primary btn-block"
            type="submit" value="Login">Login
    </button>

    {% if form.errors %}
    <div class="alert alert-danger">
        <button type="button" class="close"
                data-dismiss="alert" aria-hidden="true">×
        </button>

        Por favor, verifique o Email e/ou Senha informados
    </div>
    {% endif %}
    <a href="{% url 'cadastrar' %}">Registre-se</a>
</form>
{% endblock %}

usuarios/templates/registrar.html
{% extends 'base_usuario.html' %}
{% block body %}
<form action="{% url 'cadastrar' %}" method="post" class="form-signin">
    {% csrf_token %}
    <h2 class="form-signin-heading">Crie seu usuário</h2>

    <input id="id_nome" name="nome" type="tex" placeholder="Nome *" class="form-control" required>
    <input id="id_email" name="email" type="email" placeholder="Email *" class="form-control" required autofocus>
    <input id="id_senha" name="senha" type="password" placeholder="Senha *" class="form-control" required>
    <hr/>
    <input id="id_fone" name="telefone" type="tel" placeholder="Telefone *" class="form-control" required>
    <input id="id_empresa" name="nome_empresa" type="text" placeholder="Empresa *" class="form-control" required>
    <hr/>
    <button type="submit" value="Login" class="btn btn-primary btn-block">Cadastrar</button>


    {% if form.errors %}
    <div class="alert alert-danger">
        <button type="button" class="close"
                data-dismiss="alert" aria-hidden="true">
        </button>
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <a href="{% url 'login' %}">Já possuo uma conta</a>

</form>
{% endblock %}